# Generated by Django 4.2.6 on 2023-12-11 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='tpoic_name',
            new_name='topic_name',
        ),
        migrations.RenameField(
            model_name='webpages',
            old_name='tpoic_name',
            new_name='topic_name',
        ),
    ]
